{
 "title": "jwt-pizza",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"http\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"db\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"factory\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", level=\"error\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"exception\"} |= ``"
    },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", level=\"warn\"} |= ``"
    }
   ]
  },
  { "title": "Row 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "pizza_service_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "pizza_service_auth_attempts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "pizza_service_http_requests_all_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_http_requests_total{method=\"DELETE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_http_requests_total{method=\"GET\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_http_requests_total{method=\"POST\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_http_requests_total{method=\"PUT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory & CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_service_memory_usage_percent",
     "legendFormat": "__auto"
    },
    { "expr": "pizza_service_cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "pizza_service_pizza_factory_latency_avg_milliseconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_endpoint_latency_avg_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "pizza_service_pizzas_sold_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "pizza_service_pizza_creation_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_service_revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "pizza_service_pizza_factory_latency_avg_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}